default: &default
  adapter: postgresql
  user: <%= ENV['ELEARNIO_DB_USER'] %>
  password: <%= ENV['ELEARNIO_DB_PASSWORD'] %>
  host: <%= ENV['ELEARNIO_DB_HOST'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: elearnio_development

test:
  <<: *default
  database: elearnio_test

#production
#  <<: *default
#  database: elearnio_production